<a href="https://colab.research.google.com/github/PopocaOrtiz/test-pytorch/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals

In [ ]:
import torch
print(torch.__version__)

2.3.1+cu121


In [ ]:
# creating tensors

## scalar

scalar = torch.tensor(1290)

scalar

scalar.shape

torch.Size([])

In [ ]:
scalar.ndim

0

In [ ]:
## 1-dimension
one_dimension = torch.tensor([1,2,3])
one_dimension
one_dimension.ndim
list(one_dimension)
one_dimension[2].item()
one_dimension.shape

torch.Size([3])

In [ ]:
## n-dimension

n_dimension = torch.tensor([[1,2],[3,4]])
print('shape', n_dimension.shape)
print('first row', n_dimension[0])

shape torch.Size([2, 2])
first row tensor([1, 2])


In [ ]:
n_dimension = torch.tensor([[1,2,3],[4,5]])

### random tensors

In [ ]:
rdt = torch.rand(2,2,2)
rdt

tensor([[[0.0485, 0.6199],
         [0.2914, 0.1417]],

        [[0.0349, 0.2753],
         [0.0092, 0.2249]]])

# Creating tensors using range

In [3]:
import torch
one_hundred = torch.arange(1,101, step=5)
one_hundred

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
        91, 96])

# Creating tensors using other tensors' shapte

In [5]:
one_hundred_zeros = torch.zeros_like(input=one_hundred)
one_hundred_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

In [11]:
assert torch.int64 == torch.tensor([1,2,3]).dtype
assert torch.float32 == torch.tensor([1.,2.,3.]).dtype

In [16]:
# changing the type
float32_tensor = torch.tensor([1.,2.,3.])
print(float32_tensor)
float16_tensor = float32_tensor.type(torch.half)
print(float16_tensor)
print(float16_tensor.dtype)

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float16)
torch.float16


In [18]:
torch.tensor([1, 2, 3]) * torch.tensor([2., 2.0, 2.0])

tensor([2., 4., 6.])

In [20]:
torch.tensor([1, 2, 3], dtype=torch.int64) * torch.tensor([1., 2., 3.], dtype=torch.half)

tensor([1., 4., 9.], dtype=torch.float16)

# Manipulating tensors

In [24]:
print(torch.tensor([1., 2., 3.]) + 10)
print(torch.tensor([1., 2., 3.]) + torch.tensor(10))
print(torch.tensor([1., 2., 3.]) + torch.tensor([10, 10, 10]))

tensor([11., 12., 13.])
tensor([11., 12., 13.])
tensor([11., 12., 13.])


In [4]:
import torch
torch.matmul(torch.tensor([[1,2,3],[4,5,6]]), torch.tensor([[7,8],[9,10],[11,12]]))

tensor([[ 58,  64],
        [139, 154]])

# manual vector dot product
- checking the time

In [7]:
%%time
value = 0
tensor = torch.tensor([1,2,3])
for x in range(len(tensor)):
  value += tensor[x]
print(value)

tensor(6)
CPU times: user 4.61 ms, sys: 141 µs, total: 4.75 ms
Wall time: 17.8 ms


In [14]:
torch.rand(1,1,1)

tensor([[[0.0308]]])

# matrix multiplication

In [19]:
mat1 = torch.rand(2,3)
mat2 = torch.rand(3,2)
print(mat1.shape)
print(mat1)
print(mat2.shape)
print(mat2)
rest = mat1 @ mat2
print(rest)

torch.Size([2, 3])
tensor([[0.6730, 0.0908, 0.9645],
        [0.4370, 0.6787, 0.7835]])
torch.Size([3, 2])
tensor([[0.7316, 0.9213],
        [0.2907, 0.0754],
        [0.9901, 0.6031]])
tensor([[1.4737, 1.2085],
        [1.2927, 0.9263]])


## using transpose so the matrix multiplication *works*

In [22]:
# using transpose so the dimensions fit
torch.mm(torch.rand(3,2), torch.rand(3,2).T)

tensor([[0.6101, 0.7480, 1.0710],
        [0.4374, 0.5954, 0.8384],
        [0.3799, 0.4369, 0.6325]])

In [28]:
tensor = torch.rand(2,4)

print(tensor)

res = torch.matmul(tensor, tensor.T)

print(res)

tensor([[0.3911, 0.8662, 0.7738, 0.2741],
        [0.0714, 0.2870, 0.0598, 0.0579]])
tensor([[1.5771, 0.3387],
        [0.3387, 0.0944]])


# fint the min an max

In [29]:
# agregations (from a lot of numbers to less numbers)
tensor = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(tensor.min(), torch.min(tensor))

tensor(1) tensor(1)


In [32]:
print(tensor[1].max())

tensor(6)


# calculate the mean
*requires changing the dtype if its an integer*

In [8]:
import torch
tensor = torch.tensor([1,2,3,0,10,2])
print('mean', tensor.type(torch.float32).mean())

for i,x in enumerate(tensor):
  print(i,x)

mean tensor(3.)
0 tensor(1)
1 tensor(2)
2 tensor(3)
3 tensor(0)
4 tensor(10)
5 tensor(2)


# Index of min and max

In [5]:
tensor.argmin()

tensor(3)

In [6]:
tensor.argmax()

tensor(4)

# reshape

In [22]:
tensor = torch.arange(0, 100, 10)
print(tensor)
print(tensor.shape)

# adds a dimension on the outside
print(tensor.reshape(1, 10))
# adds a dimension on the inside
print(tensor.reshape(10, 1))

# separate the tensor in diferent tensors (something like explode?)
print(tensor.reshape(5, 2))

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
torch.Size([10])
tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])
tensor([[ 0],
        [10],
        [20],
        [30],
        [40],
        [50],
        [60],
        [70],
        [80],
        [90]])
tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])


In [26]:
tensor = torch.arange(0, 27, 3)
print(tensor)
print(tensor.reshape(3,3))

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24])
tensor([[ 0,  3,  6],
        [ 9, 12, 15],
        [18, 21, 24]])


# Views
*views share the same memory*

In [41]:
tensor9 = torch.rand(12).view(4,3)
print(tensor9)
tensor9[:,0] = 7
tensor9[1,:] = 3
print(tensor9)

tensor([[0.2072, 0.4212, 0.0269],
        [0.5948, 0.3892, 0.8186],
        [0.8118, 0.4736, 0.1606],
        [0.9915, 0.5404, 0.9787]])
tensor([[7.0000, 0.4212, 0.0269],
        [3.0000, 3.0000, 3.0000],
        [7.0000, 0.4736, 0.1606],
        [7.0000, 0.5404, 0.9787]])


# stacks

In [53]:
# Stacking tensors
tensor = torch.rand(3)
stacked = torch.stack([tensor, tensor, tensor], dim=0)
print(stacked)
stacked[1][1] = 0.3333
print(stacked)

# stacked with changed dimensions
tensor = torch.rand(6)
print(tensor)
stacked = torch.stack([tensor, tensor], dim=1)
print(stacked)

tensor([[0.0743, 0.6703, 0.9137],
        [0.0743, 0.6703, 0.9137],
        [0.0743, 0.6703, 0.9137]])
tensor([[0.0743, 0.6703, 0.9137],
        [0.0743, 0.3333, 0.9137],
        [0.0743, 0.6703, 0.9137]])
tensor([0.7156, 0.6520, 0.6669, 0.6058, 0.1281, 0.4281])
tensor([[0.7156, 0.7156],
        [0.6520, 0.6520],
        [0.6669, 0.6669],
        [0.6058, 0.6058],
        [0.1281, 0.1281],
        [0.4281, 0.4281]])


In [62]:
tensor = torch.rand(3)
print(tensor)
stacked = torch.stack([tensor, tensor, tensor], dim=1)
print(stacked)
stacked = torch.vstack([tensor, tensor, tensor])
print(stacked)
print()

# horizontal
stacked = torch.hstack([tensor, tensor, tensor])
print(stacked)

tensor([0.7547, 0.1431, 0.5759])
tensor([[0.7547, 0.7547, 0.7547],
        [0.1431, 0.1431, 0.1431],
        [0.5759, 0.5759, 0.5759]])
tensor([[0.7547, 0.1431, 0.5759],
        [0.7547, 0.1431, 0.5759],
        [0.7547, 0.1431, 0.5759]])

tensor([0.7547, 0.1431, 0.5759, 0.7547, 0.1431, 0.5759, 0.7547, 0.1431, 0.5759])


# Squeeze: removes dimensions of size=1

In [67]:
tensor = torch.arange(0, 16).reshape(4,4)
print(tensor)
tensor = torch.stack([tensor])
print(tensor, tensor.shape)
tensor = torch.squeeze(tensor)
print(tensor, tensor.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]]]) torch.Size([1, 4, 4])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]) torch.Size([4, 4])


# unsqueeze

In [80]:
tensor = torch.arange(0, 27).reshape(3,3,3)
print(tensor)
unsqueeze = tensor.unsqueeze(3)
print(unsqueeze)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])
tensor([[[[ 0],
          [ 1],
          [ 2]],

         [[ 3],
          [ 4],
          [ 5]],

         [[ 6],
          [ 7],
          [ 8]]],


        [[[ 9],
          [10],
          [11]],

         [[12],
          [13],
          [14]],

         [[15],
          [16],
          [17]]],


        [[[18],
          [19],
          [20]],

         [[21],
          [22],
          [23]],

         [[24],
          [25],
          [26]]]])


# permute
*rearranges the dimensions*
*its also a view*

In [85]:
x = torch.rand(2,3,4)
print(x.shape)
print(x.size())
print(x)

print()

y = torch.permute(x, (2,0,1))
print(y.shape)
print(y)

torch.Size([2, 3, 4])
torch.Size([2, 3, 4])
tensor([[[0.5027, 0.8188, 0.3000, 0.6320],
         [0.2732, 0.7008, 0.1501, 0.5342],
         [0.8264, 0.0485, 0.1937, 0.5420]],

        [[0.8590, 0.4347, 0.2954, 0.3936],
         [0.7198, 0.1789, 0.7446, 0.6528],
         [0.7667, 0.0342, 0.0884, 0.8327]]])

torch.Size([4, 2, 3])
tensor([[[0.5027, 0.2732, 0.8264],
         [0.8590, 0.7198, 0.7667]],

        [[0.8188, 0.7008, 0.0485],
         [0.4347, 0.1789, 0.0342]],

        [[0.3000, 0.1501, 0.1937],
         [0.2954, 0.7446, 0.0884]],

        [[0.6320, 0.5342, 0.5420],
         [0.3936, 0.6528, 0.8327]]])


In [90]:
# manually iterating

tensor = torch.arange(0, 27*3, 3).reshape(3,3,3)
print(tensor)
for i in range(len(tensor)):
  for j in range(len(tensor[i])):
    for k in range(len(tensor[i][j])):
      print(tensor[i, j, k])


tensor([[[ 0,  3,  6],
         [ 9, 12, 15],
         [18, 21, 24]],

        [[27, 30, 33],
         [36, 39, 42],
         [45, 48, 51]],

        [[54, 57, 60],
         [63, 66, 69],
         [72, 75, 78]]])
tensor(0)
tensor(3)
tensor(6)
tensor(9)
tensor(12)
tensor(15)
tensor(18)
tensor(21)
tensor(24)
tensor(27)
tensor(30)
tensor(33)
tensor(36)
tensor(39)
tensor(42)
tensor(45)
tensor(48)
tensor(51)
tensor(54)
tensor(57)
tensor(60)
tensor(63)
tensor(66)
tensor(69)
tensor(72)
tensor(75)
tensor(78)


# Reproducibility
*reduce randomness in neural networks*
- uses a **random seed**